Repository anjalit03/Dazzle-and-Delight, pull requests merged in 2024-10, with the labels that each got.

#4 Create CONTRIBUTING.md
  CONTRIBUTING.md
Labels: documentation, hacktoberfest

#5 fix calender in landing page
  css/style.css
  css/style2.css
Labels: bug, good first issue, hacktoberfest

#40 Login page improvements
  html/css/login.css
  html/login.html
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#42 solve goa image bug ,change ui, add search box
  html/css/location.css
  html/location.html
  html/photos/Lucknow.jpg
  html/photos/ahmedabad.jpg
  html/photos/hyderabad.jpg
  html/photos/pune.jpg
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#79 Enhancement in Contact Us Page
  html/css/contact_us.css
Labels: bug, hacktoberfest, hacktoberfest-accepted

#83 added synopsis for events
  html/css/event.css
Labels: hacktoberfest

#88 updated some files to maintain clear coding
  CONTRIBUTING.md
  html/about_us.html
  html/contact_us.html
  html/css/add_event.css
  html/css/card.css
  html/css/genre.css
  html/css/myStyle.css
  html/css/style.css
  html/css/style2.css
  html/index.html
Labels: bug, enhancement, hacktoberfest, hacktoberfest-accepted
